# Generated by Django 6.0.5 on 2026-05-27 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('intro', 'Intro'), ('texte', 'Texte'), ('image', 'Image'), ('gallery', 'Galerie'), ('video', 'Vidéo'), ('audio', 'Audio'), ('citation', 'Citation'), ('timeline', 'Timeline'), ('embed', 'Embed')], max_length=20)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('contenu', models.TextField(blank=True)),
                ('citation_auteur', models.CharField(blank=True, max_length=200)),
                ('citation_large', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='reportages/images/')),
                ('image_caption', models.CharField(blank=True, max_length=500)),
                ('image_credit', models.CharField(blank=True, max_length=200)),
                ('image_fullbleed', models.BooleanField(default=False)),
                ('video_fichier', models.FileField(blank=True, null=True, upload_to='reportages/videos/')),
                ('video_url', models.URLField(blank=True)),
                ('video_titre', models.CharField(blank=True, max_length=255)),
                ('video_description', models.CharField(blank=True, max_length=500)),
                ('video_duree', models.CharField(blank=True, max_length=20)),
                ('video_thumbnail', models.ImageField(blank=True, null=True, upload_to='reportages/thumbnails/')),
                ('audio_fichier', models.FileField(blank=True, null=True, upload_to='reportages/audios/')),
                ('audio_titre', models.CharField(blank=True, max_length=255)),
                ('audio_description', models.CharField(blank=True, max_length=500)),
                ('audio_duree', models.CharField(blank=True, max_length=20)),
                ('embed_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Bloc',
                'verbose_name_plural': 'Blocs',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reportages/gallery/')),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('credit', models.CharField(blank=True, max_length=200)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('bloc', models.ForeignKey(limit_choices_to={'type': 'gallery'}, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='reportage.bloc')),
            ],
            options={
                'verbose_name': 'Image de galerie',
                'verbose_name_plural': 'Images de galerie',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Reportage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='reportages/covers/')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('review', 'En révision'), ('published', 'Publié')], default='draft', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='reportages/og/')),
                ('reading_time', models.PositiveIntegerField(default=0, editable=False, help_text='Calculé automatiquement (mots / 200). Ne pas modifier.')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reportage',
                'verbose_name_plural': 'Reportages',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='bloc',
            name='reportage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocs', to='reportage.reportage'),
        ),
        migrations.CreateModel(
            name='ReportageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reportage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='reportage.reportage')),
            ],
            options={
                'verbose_name': 'Vue',
                'verbose_name_plural': 'Vues',
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_label', models.CharField(help_text="Ex: '12 janvier 2024', 'Été 1994', '3h42'", max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='reportages/timeline/')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('bloc', models.ForeignKey(limit_choices_to={'type': 'timeline'}, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='reportage.bloc')),
            ],
            options={
                'verbose_name': 'Événement de timeline',
                'verbose_name_plural': 'Événements de timeline',
                'ordering': ['ordre'],
            },
        ),
        migrations.AddIndex(
            model_name='reportage',
            index=models.Index(fields=['slug'], name='reportage_r_slug_160a61_idx'),
        ),
        migrations.AddIndex(
            model_name='reportage',
            index=models.Index(fields=['status'], name='reportage_r_status_ffb736_idx'),
        ),
        migrations.AddIndex(
            model_name='reportage',
            index=models.Index(fields=['published_at'], name='reportage_r_publish_9e325d_idx'),
        ),
        migrations.AddIndex(
            model_name='reportage',
            index=models.Index(fields=['featured'], name='reportage_r_feature_7fee3e_idx'),
        ),
        migrations.AddIndex(
            model_name='bloc',
            index=models.Index(fields=['ordre'], name='reportage_b_ordre_d57354_idx'),
        ),
        migrations.AddIndex(
            model_name='bloc',
            index=models.Index(fields=['type'], name='reportage_b_type_89a357_idx'),
        ),
        migrations.AddIndex(
            model_name='reportageview',
            index=models.Index(fields=['reportage', 'ip_hash'], name='reportage_r_reporta_fc10dd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reportageview',
            unique_together={('reportage', 'ip_hash')},
        ),
    ]
