# Generated by Django 6.0.5 on 2026-06-02 19:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloc',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
