# Generated by Django 6.0.5 on 2026-06-06 07:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportage', '0002_bloc_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('author_role', models.CharField(blank=True, help_text="Titre/rôle de l'auteur", max_length=255)),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='quotes/%Y/%m/')),
                ('source', models.CharField(blank=True, help_text='Livre, article, etc.', max_length=500)),
                ('source_url', models.URLField(blank=True, help_text='Lien vers la source')),
                ('alignment', models.CharField(choices=[('left', 'Gauche'), ('center', 'Centré'), ('right', 'Droite')], default='center', max_length=20)),
                ('accent_color', models.CharField(default='#000000', help_text="Couleur d'accent (format hex)", max_length=7)),
                ('background_color', models.CharField(blank=True, default='#f5f5f5', max_length=7)),
                ('border_style', models.CharField(choices=[('left', 'Barre gauche'), ('top', 'Barre haut'), ('none', 'Aucune')], default='left', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Citations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameField(
            model_name='bloc',
            old_name='audio_description',
            new_name='video_caption',
        ),
        migrations.RemoveField(
            model_name='bloc',
            name='audio_duree',
        ),
        migrations.RemoveField(
            model_name='bloc',
            name='audio_fichier',
        ),
        migrations.RemoveField(
            model_name='bloc',
            name='audio_titre',
        ),
        migrations.RemoveField(
            model_name='bloc',
            name='video_description',
        ),
        migrations.RemoveField(
            model_name='bloc',
            name='video_duree',
        ),
        migrations.RemoveField(
            model_name='bloc',
            name='video_fichier',
        ),
        migrations.RemoveField(
            model_name='bloc',
            name='video_thumbnail',
        ),
        migrations.RemoveField(
            model_name='bloc',
            name='video_titre',
        ),
        migrations.RemoveField(
            model_name='bloc',
            name='video_url',
        ),
        migrations.AddField(
            model_name='bloc',
            name='video_vimeo_url',
            field=models.URLField(blank=True, help_text='URL Vimeo'),
        ),
        migrations.AddField(
            model_name='bloc',
            name='video_youtube_url',
            field=models.URLField(blank=True, help_text='URL YouTube'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('video', 'Vidéo'), ('audio', 'Audio'), ('document', 'Document')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='media_files/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov', 'mp3', 'wav', 'pdf', 'doc', 'docx'])])),
                ('video_format', models.CharField(blank=True, choices=[('mp4', 'MP4 (H.264)'), ('webm', 'WebM (VP9)'), ('mov', 'MOV')], max_length=10, null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Durée en secondes', null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, help_text='Thumbnail personnalisée', null=True, upload_to='video_thumbnails/%Y/%m/%d/')),
                ('file_size', models.BigIntegerField(blank=True, help_text='Taille en bytes', null=True)),
                ('mime_type', models.CharField(blank=True, max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transcription', models.TextField(blank=True, help_text="Transcription de la vidéo pour l'accessibilité")),
                ('subtitles_file', models.FileField(blank=True, help_text='Fichier SRT ou VTT', null=True, upload_to='subtitles/%Y/%m/%d/')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_media_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Fichiers média',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='bloc',
            name='audio',
            field=models.ForeignKey(blank=True, limit_choices_to={'media_type': 'audio'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_blocs', to='reportage.mediafile'),
        ),
        migrations.AddField(
            model_name='bloc',
            name='video_local',
            field=models.ForeignKey(blank=True, limit_choices_to={'media_type': 'video'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocs', to='reportage.mediafile'),
        ),
        migrations.CreateModel(
            name='OptimizedImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='optimized_images/%Y/%m/%d/')),
                ('image_thumb', models.ImageField(blank=True, upload_to='optimized_images/thumbs/%Y/%m/%d/')),
                ('image_small', models.ImageField(blank=True, upload_to='optimized_images/small/%Y/%m/%d/')),
                ('image_medium', models.ImageField(blank=True, upload_to='optimized_images/medium/%Y/%m/%d/')),
                ('image_large', models.ImageField(blank=True, upload_to='optimized_images/large/%Y/%m/%d/')),
                ('alt_text', models.CharField(help_text='Texte alternatif (SEO)', max_length=255)),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('credit', models.CharField(blank=True, max_length=255)),
                ('width', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('aspect_ratio', models.CharField(blank=True, editable=False, max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='optimized_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Images optimisées',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AlterField(
            model_name='bloc',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocs', to='reportage.optimizedimage'),
        ),
        migrations.AddField(
            model_name='bloc',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocs', to='reportage.quote'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['media_type', '-uploaded_at'], name='reportage_m_media_t_11237b_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['uploaded_by'], name='reportage_m_uploade_57d3ed_idx'),
        ),
    ]
