# Generated by Django 6.0.5 on 2026-06-08 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportage', '0003_quote_rename_audio_description_bloc_video_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='reportage.optimizedimage'),
        ),
        migrations.AlterField(
            model_name='reportage',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportage_covers', to='reportage.optimizedimage'),
        ),
        migrations.AlterField(
            model_name='reportage',
            name='og_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportage_og_images', to='reportage.optimizedimage'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_events', to='reportage.optimizedimage'),
        ),
    ]
