# Generated by Django 6.0.5 on 2026-06-10 13:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportage', '0004_alter_galleryimage_image_alter_reportage_cover_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediafile',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Fichier média', 'verbose_name_plural': 'Fichiers média'},
        ),
        migrations.AlterModelOptions(
            name='optimizedimage',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Image optimisée', 'verbose_name_plural': 'Images optimisées'},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['-created_at'], 'verbose_name': 'Citation', 'verbose_name_plural': 'Citations'},
        ),
        migrations.AddField(
            model_name='optimizedimage',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='Taille originale en bytes', null=True),
        ),
        migrations.AlterField(
            model_name='optimizedimage',
            name='alt_text',
            field=models.CharField(help_text='Texte alternatif (SEO / Accessibilité)', max_length=255),
        ),
        migrations.AlterField(
            model_name='optimizedimage',
            name='caption',
            field=models.CharField(blank=True, help_text="Légende de l'image", max_length=500),
        ),
        migrations.AlterField(
            model_name='optimizedimage',
            name='credit',
            field=models.CharField(blank=True, help_text='Crédits photographiques', max_length=255),
        ),
        migrations.AlterField(
            model_name='optimizedimage',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='optimizedimage',
            name='image',
            field=models.ImageField(help_text='Image source (sera convertie en WEBP pour les variantes)', upload_to='optimized_images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='optimizedimage',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='date_label',
            field=models.CharField(help_text="Ex: '12 janvier 2024', 'Été 1994'", max_length=100),
        ),
        migrations.AddIndex(
            model_name='optimizedimage',
            index=models.Index(fields=['id'], name='reportage_o_id_105cb3_idx'),
        ),
        migrations.AddIndex(
            model_name='optimizedimage',
            index=models.Index(fields=['uploaded_by'], name='reportage_o_uploade_679d38_idx'),
        ),
        migrations.AddIndex(
            model_name='optimizedimage',
            index=models.Index(fields=['-uploaded_at'], name='reportage_o_uploade_33e733_idx'),
        ),
    ]
