# Generated by Django 6.0.5 on 2026-08-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportage', '0005_alter_mediafile_options_alter_optimizedimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizedimage',
            name='image_large_url',
            field=models.URLField(blank=True, editable=False, verbose_name='URL large Supabase'),
        ),
        migrations.AddField(
            model_name='optimizedimage',
            name='image_medium_url',
            field=models.URLField(blank=True, editable=False, verbose_name='URL medium Supabase'),
        ),
        migrations.AddField(
            model_name='optimizedimage',
            name='image_small_url',
            field=models.URLField(blank=True, editable=False, verbose_name='URL small Supabase'),
        ),
        migrations.AddField(
            model_name='optimizedimage',
            name='image_thumb_url',
            field=models.URLField(blank=True, editable=False, verbose_name='URL thumbnail Supabase'),
        ),
        migrations.AddField(
            model_name='optimizedimage',
            name='image_url',
            field=models.URLField(blank=True, editable=False, verbose_name='URL originale Supabase'),
        ),
    ]
