# Generated by Django 6.0.5 on 2026-08-15 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportage', '0006_optimizedimage_image_large_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optimizedimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Image source (sera convertie en WEBP pour les variantes)', null=True, upload_to='optimized_images/%Y/%m/%d/'),
        ),
    ]
