# Generated by Django 6.0.5 on 2026-08-15 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportage', '0007_alter_optimizedimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='file_url',
            field=models.URLField(blank=True, editable=False, verbose_name='URL Supabase'),
        ),
    ]
