# Generated by Django 6.0.4 on 2026-05-07 05:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Nom de la société')),
                ('contact_name', models.CharField(max_length=150, verbose_name='Nom du contact')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Annonceur',
                'verbose_name_plural': 'Annonceurs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='Titre de la pub')),
                ('image', models.ImageField(upload_to='ads/%Y/%m/', verbose_name='Image')),
                ('destination_url', models.URLField(verbose_name='URL de destination')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Texte alternatif')),
                ('format', models.CharField(choices=[('banner_top', 'Bannière haut de page'), ('banner_bottom', 'Bannière bas de page'), ('sidebar', 'Sidebar'), ('in_content', "Dans l'article"), ('sticky_footer', 'Footer collant')], db_index=True, max_length=20)),
                ('target_category', models.CharField(choices=[('all', 'Toutes catégories'), ('medical', 'Médical'), ('travel', 'Voyage'), ('technology', 'Technologie'), ('education', 'Éducation'), ('lifestyle', 'Lifestyle'), ('science', 'Science'), ('legal', 'Juridique'), ('finance', 'Finance')], db_index=True, default='all', max_length=20, verbose_name='Catégorie ciblée')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Active'), ('paused', 'En pause'), ('expired', 'Expirée'), ('archived', 'Archivée')], db_index=True, default='draft', max_length=10)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Début')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Fin (vide = illimitée)')),
                ('priority', models.PositiveSmallIntegerField(default=1, help_text='Plus le chiffre est élevé, plus la pub est prioritaire.', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_impressions', models.PositiveIntegerField(blank=True, null=True, verbose_name='Impressions max (vide = illimité)')),
                ('max_clicks', models.PositiveIntegerField(blank=True, null=True, verbose_name='Clics max (vide = illimité)')),
                ('impressions_count', models.PositiveIntegerField(default=0, editable=False)),
                ('clicks_count', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ads', to='ads.advertiser')),
            ],
            options={
                'verbose_name': 'Publicité',
                'verbose_name_plural': 'Publicités',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdClick',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('referer', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='ads.ad')),
            ],
            options={
                'verbose_name': 'Clic',
                'verbose_name_plural': 'Clics',
                'indexes': [models.Index(fields=['ad', 'created_at'], name='ads_adclick_ad_id_cff191_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdImpression',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('referer', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='ads.ad')),
            ],
            options={
                'verbose_name': 'Impression',
                'verbose_name_plural': 'Impressions',
                'indexes': [models.Index(fields=['ad', 'created_at'], name='ads_adimpre_ad_id_e3dcc3_idx'), models.Index(fields=['ip_address', 'ad'], name='ads_adimpre_ip_addr_b926dc_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['status', 'format', 'target_category'], name='ads_ad_status_49a095_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['start_date', 'end_date'], name='ads_ad_start_d_26c3bf_idx'),
        ),
    ]
