# Generated by Django 6.0.5 on 2026-08-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='image_url',
            field=models.URLField(blank=True, editable=False, verbose_name="URL de l'image"),
        ),
        migrations.AddField(
            model_name='advertiser',
            name='image_url',
            field=models.URLField(blank=True, editable=False, verbose_name='URL Supabase'),
        ),
    ]
