# Generated by Django 6.0.5 on 2026-06-25 20:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_en',
            field=models.TextField(null=True, validators=[django.core.validators.MinLengthValidator(100)]),
        ),
        migrations.AddField(
            model_name='post',
            name='content_es',
            field=models.TextField(null=True, validators=[django.core.validators.MinLengthValidator(100)]),
        ),
        migrations.AddField(
            model_name='post',
            name='content_fr',
            field=models.TextField(null=True, validators=[django.core.validators.MinLengthValidator(100)]),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ht',
            field=models.TextField(null=True, validators=[django.core.validators.MinLengthValidator(100)]),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt_en',
            field=models.TextField(help_text='Résumé affiché dans les listes.', max_length=500, null=True, validators=[django.core.validators.MinLengthValidator(30)]),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt_es',
            field=models.TextField(help_text='Résumé affiché dans les listes.', max_length=500, null=True, validators=[django.core.validators.MinLengthValidator(30)]),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt_fr',
            field=models.TextField(help_text='Résumé affiché dans les listes.', max_length=500, null=True, validators=[django.core.validators.MinLengthValidator(30)]),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt_ht',
            field=models.TextField(help_text='Résumé affiché dans les listes.', max_length=500, null=True, validators=[django.core.validators.MinLengthValidator(30)]),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description_es',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description_fr',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description_ht',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_title_es',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_title_fr',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_title_ht',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='source_language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('es', 'Español'), ('ht', 'Kreyòl Ayisyen')], db_index=True, default='fr', help_text="Langue dans laquelle l'article a été rédigé.", max_length=2),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AddField(
            model_name='post',
            name='title_es',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AddField(
            model_name='post',
            name='title_fr',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ht',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
